exclude: ['node_modules']
pygments: true

author:
    name: Phillip Whisenhunt
    github: pwhisenhunt
    twitter: pwhisenhunt
    gravatar: http://en.gravatar.com/userimage/34277957/9af38b589e9200f0ad9eb274226337c4.jpg?size=100
    linkedin: whisenhunt